// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqozxsdaptbjxiicjqat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxb3p4c2RhcHRianhpaWNqcWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDA3NzQsImV4cCI6MjA2NTA3Njc3NH0.VgQr8nAttOPsE4e6AU1C2X-qq3YboCi05UmpipgkgB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);